services:
  - type: web
    name: docrolds-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_CUSTOMER_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
